/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kumarohi' at '5/30/17 1:14 PM' with Gradle 2.14.1
 *
 * @author kumarohi, @date 5/30/17 1:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
